version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: America/Chicago
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    labels:
      - dependencies
      - javascript
    groups:
      production-dependencies:
        dependency-type: production
        patterns:
          - '*'
      development-dependencies:
        dependency-type: development
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:30'
      timezone: America/Chicago
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - '*'
